# our base image
FROM mongo:3.4.2

# copy files required for the app to run
#COPY app.py /usr/src/app/
#COPY templates/index.html /usr/src/app/templates/

# tell the port number the container should expose, for Spark web is 4567 usually
EXPOSE 4567

# run the application
# CMD ["python", "/usr/src/app/app.py"]